### ISSUE TITLE
Document process for starting the database

### ISSUE THREAD

**Issue by nickkpope** [nickkpope/commpute#19]
Can you tell us what needs to be done in order to start up the database and get it working with the app?

I got an account setup with Digital Ocean and want to get things up and running. I also want a sandbox on my own machine to test with.

**Comment by bipvanwinkle** [comment]
It was pretty easy on my end. I don't know what it will be like on other systems. The installation process also starts up the mongo daemon. Once this is set up the flask-pymongo extensions connects with the database automatically. Honestly, I think that is all that needs to be done. 

This is the link for the installation guide. 
http://docs.mongodb.org/manual/installation/

Does this help?

**Comment by nickkpope** [comment]
I installed flask-pymongo but when I ran the app it said "Connection Refused" as if it couldn't find the database… Were there any files that weren't committed?

**Comment by bipvanwinkle** [comment]
No. Did you also install mongodb?

**Comment by nickkpope** [comment]
"Yeah, of course I did that. It would be totally silly of me to try to use a database that is not installed...", he said in a very sarcastic tone.
