### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by nickkpope** [nickkpope/commpute#2]
We need to be able to authenticate with:
g+
Facebook
Twitter
(any others that would be easy)

**Comment by bipvanwinkle** [comment]
I think that this is going to have to wait till the next milestone.

**Comment by nickkpope** [comment]
No worries. It's a tricky thing.

**Comment by bipvanwinkle** [comment]
Oauth for twitter is now working. Just so you know...

**Comment by nickkpope** [comment]
Sick! Hack your way to glory!
