### ISSUE TITLE
Database Design - Object Handle

### ISSUE THREAD

**Issue by bipvanwinkle** [nickkpope/commpute#26]
Common Operations
- Objects in application need to be serialized and stored in database
- Database documents need to be turned into application objects

Questions
- What is the advantage of using inheritance in the model?

**Comment by nickkpope** [comment]
Yeah, it seems that type of no-SQL environment doesn't benefit as strongly with a base class inheritance approach. I think those types of classes give us a way to access that data in a friendlier way, as well as wrap manipulations of that data in those classes. Your thoughts?

**Comment by bipvanwinkle** [comment]
So, I decided to just write the save/load methods myself. I am sure there is a better way to do this, but for now I think that the simple approach is best.
