### ISSUE TITLE
Track connection requests with another participant.

### ISSUE THREAD

**Issue by nickkpope** [nickkpope/commpute#4]
We need to store connection requests.

**Comment by bipvanwinkle** [comment]
My plan is something like this...
Participant:
    uptime
    name
    requests
    ....

```
Where requests are all the people who have requested to join their network
```

How does this sound?

**Comment by nickkpope** [comment]
Yeah, I think that should work. I can't think off circumstance where a user would want to see all his or her outgoing requests. That query might be a bit slow.

**Comment by bipvanwinkle** [comment]
Actually on second thought we might as well create a new collection in the database for requests. That way we can handle both sides without much trouble.

**Comment by nickkpope** [comment]
Yeah, we might as well keep our options open.
